Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                  count    min threads    max threads
-----------------  -------  -------------  -------------
all                      1              1              1
filter_alignments        2              1              1
total                    3              1              1

Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (2):
	filter_alignments
	filter_alignments
Select jobs to execute...
Selected jobs (2):
	filter_alignments
	filter_alignments
Resources after job selection: {'_cores': 2, '_nodes': 9223372036854775805}

[Thu Aug 25 15:10:48 2022]
rule filter_alignments:
    input: test/bam/raw/lib002.bam, test/inputs/keep.bed
    output: test/bam/frag/lib002_filt.bam
    jobid: 2
    wildcards: library_id=lib002
    resources: tmpdir=/tmp, mem_mb=5000


        workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam
        
 singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam'
Activating singularity image ${HOME}/sing_containers/cfdna_wgs.1.0.0

[Thu Aug 25 15:10:48 2022]
rule filter_alignments:
    input: test/bam/raw/lib001.bam, test/inputs/keep.bed
    output: test/bam/frag/lib001_filt.bam
    jobid: 1
    wildcards: library_id=lib001
    resources: tmpdir=/tmp, mem_mb=5000


        workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam
        
 singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam'
Activating singularity image ${HOME}/sing_containers/cfdna_wgs.1.0.0
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 36, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam'' returned non-zero exit status 255.

[Thu Aug 25 15:10:48 2022]
Error in rule filter_alignments:
    jobid: 2
    output: test/bam/frag/lib002_filt.bam
    shell:
        
        workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 36, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam'' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 15 of /home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk:
Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam'' returned non-zero exit status 255.
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 15, in __rule_filter_alignments

RuleException:
CalledProcessError in line 15 of /home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk:
Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib002.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib002_filt.bam'' returned non-zero exit status 255.
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 15, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 36, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam'' returned non-zero exit status 255.

[Thu Aug 25 15:10:48 2022]
Error in rule filter_alignments:
    jobid: 1
    output: test/bam/frag/lib001_filt.bam
    shell:
        
        workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 36, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam'' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 15 of /home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk:
Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam'' returned non-zero exit status 255.
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 15, in __rule_filter_alignments

RuleException:
CalledProcessError in line 15 of /home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk:
Command ' singularity  exec --home /home/jeszyman/repos/cfdna-frag --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake ${HOME}/sing_containers/cfdna_wgs.1.0.0 bash -c 'workflow/scripts/filter_alignments.sh test/bam/raw/lib001.bam                                               test/inputs/keep.bed                                               test/tmp                                               4                                               test/bam/frag/lib001_filt.bam'' returned non-zero exit status 255.
  File "/home/jeszyman/repos/cfdna-frag/workflow/frag_bed.smk", line 15, in __rule_filter_alignments
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/jeszyman/repos/cfdna-frag/.snakemake/log/2022-08-25T151048.013909.snakemake.log
unlocking
removing lock
removing lock
removed all locks
